batch_size: 16
checkpoint: null
device: cuda:0
exp_name: est_coord_bsz_16_lr_0.001_mse_rot_False_20250417_145925
learning_rate: 0.001
learning_rate_min: 1.0e-08
log_interval: 100
max_iter: 3000
model_type: est_coord
num_workers: 4
obj_name: power_drill
point_num: 1024
robot: galbot
save_interval: 200
seed: 0
use_mse_loss_on_rot: false
val_interval: 200
val_num: 10
